# GPU options
GPUs: "0,1"

# Data options
root: "Project/Shape-Prior-Semi-Seg/"
dataset: "tn3k"  
ratio: 2

# Training options
manner: "semi"  # Options: ["full", "semi", "test", "self"]
mode: "train"
nEpoch: 200
batch_size: 32
num_workers: 2
load_ckpt: "best"
model: "MyModel"
expID: 3
ckpt_name: "tn3k_1"

# Optimizer options
lr: 0.001
power: 0.9
betas: [0.9, 0.999]
weight_decay: 1e-5
eps: 1e-8
mt: 0.9
nclasses: 1
band: 3
