dataset: tn3k
dataroot: "tn3k/"
workers: 2
batchSize: 16
imageSize: 64
nc: 1
nz: 100
ngf: 64
ndf: 64
niter: 5001
lrD: 0.00005
lrG: 0.00005
beta1: 0.5
ngpu: 2
netG: ""
netD: ""
clamp_lower: -0.01
clamp_upper: 0.01
Diters: 5
noBN: false
mlp_G: false
mlp_D: false
n_extra_layers: 0
experiment: "result"
adam: false
root: "Project/Shape-Prior-Semi-Seg/"
expID: 1
